# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WhatsAPIGo.Api.Miscellaneous do
  @moduledoc """
  API calls for all endpoints tagged `Miscellaneous`.
  """

  alias WhatsAPIGo.Connection
  import WhatsAPIGo.RequestBuilder

  @doc """
  Get profile pic.
  Returns the profile pic of the given user.

  ### Parameters

  - `connection` (WhatsAPIGo.Connection): Connection to server
  - `instance_key` (String.t): Instance key
  - `jid` (String.t): JID
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, WhatsAPIGo.Model.MainApiResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec instances_instance_key_misc_profile_pic_get(Tesla.Env.client, String.t, String.t, keyword()) :: {:ok, WhatsAPIGo.Model.MainApiResponse.t} | {:error, Tesla.Env.t}
  def instances_instance_key_misc_profile_pic_get(connection, instance_key, jid, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/instances/#{instance_key}/misc/profile-pic")
      |> add_param(:query, :jid, jid)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %WhatsAPIGo.Model.MainApiResponse{}},
      {400, %WhatsAPIGo.Model.MainApiResponse{}},
      {401, %WhatsAPIGo.Model.MainApiResponse{}},
      {404, %WhatsAPIGo.Model.MainApiResponse{}},
      {500, %WhatsAPIGo.Model.MainApiResponse{}}
    ])
  end

  @doc """
  Fetches the users info.
  Gets the user info for the given user ids. This does not checks if user is registered or not

  ### Parameters

  - `connection` (WhatsAPIGo.Connection): Connection to server
  - `instance_key` (String.t): Instance key
  - `data` (StructsUserInfoPayload): Data
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, WhatsAPIGo.Model.MainApiResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec instances_instance_key_misc_user_info_post(Tesla.Env.client, String.t, WhatsAPIGo.Model.StructsUserInfoPayload.t, keyword()) :: {:ok, WhatsAPIGo.Model.MainApiResponse.t} | {:error, Tesla.Env.t}
  def instances_instance_key_misc_user_info_post(connection, instance_key, data, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/instances/#{instance_key}/misc/user-info")
      |> add_param(:body, :body, data)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %WhatsAPIGo.Model.MainApiResponse{}},
      {400, %WhatsAPIGo.Model.MainApiResponse{}},
      {401, %WhatsAPIGo.Model.MainApiResponse{}},
      {404, %WhatsAPIGo.Model.MainApiResponse{}},
      {500, %WhatsAPIGo.Model.MainApiResponse{}}
    ])
  end
end
