# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WhatsAPI.Model.ButtonMessagePayload do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :buttons,
    :footer_text,
    :header_text,
    :text,
    :to
  ]

  @type t :: %__MODULE__{
    :buttons => [WhatsAPI.Model.ReplyButton.t] | nil,
    :footer_text => String.t | nil,
    :header_text => String.t | nil,
    :text => String.t | nil,
    :to => String.t | nil
  }
end

defimpl Poison.Decoder, for: WhatsAPI.Model.ButtonMessagePayload do
  import WhatsAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:buttons, :list, WhatsAPI.Model.ReplyButton, options)
  end
end

