# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WhatsAPI.Model.ContactMessagePayload do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :to,
    :vcard
  ]

  @type t :: %__MODULE__{
    :to => String.t,
    :vcard => WhatsAPI.Model.ContactMessagePayloadVcard.t
  }
end

defimpl Poison.Decoder, for: WhatsAPI.Model.ContactMessagePayload do
  import WhatsAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:vcard, :struct, WhatsAPI.Model.ContactMessagePayloadVcard, options)
  end
end

