# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WhatsAPI.Model.GroupCreatePayload do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :group_name,
    :participants
  ]

  @type t :: %__MODULE__{
    :group_name => String.t | nil,
    :participants => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: WhatsAPI.Model.GroupCreatePayload do
  def decode(value, _options) do
    value
  end
end

