# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WhatsAPI.Model.GroupInviteMessagePayload do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :caption,
    :expiry_minutes,
    :invite_code,
    :to
  ]

  @type t :: %__MODULE__{
    :caption => String.t | nil,
    :expiry_minutes => integer() | nil,
    :invite_code => String.t | nil,
    :to => String.t | nil
  }
end

defimpl Poison.Decoder, for: WhatsAPI.Model.GroupInviteMessagePayload do
  def decode(value, _options) do
    value
  end
end

