# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WhatsAPI.Model.LocationMessagePayload do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :location,
    :to,
    :url
  ]

  @type t :: %__MODULE__{
    :location => WhatsAPI.Model.LocationMessagePayloadLocation.t,
    :to => String.t,
    :url => String.t | nil
  }
end

defimpl Poison.Decoder, for: WhatsAPI.Model.LocationMessagePayload do
  import WhatsAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:location, :struct, WhatsAPI.Model.LocationMessagePayloadLocation, options)
  end
end

