# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WhatsAPI.Model.StructsListSection do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :rows,
    :title
  ]

  @type t :: %__MODULE__{
    :rows => [WhatsAPI.Model.StructsListItem.t],
    :title => String.t
  }
end

defimpl Poison.Decoder, for: WhatsAPI.Model.StructsListSection do
  import WhatsAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:rows, :list, WhatsAPI.Model.StructsListItem, options)
  end
end

