# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WhatsAPI.Model.StructsTemplateButton do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :button_id,
    :payload,
    :title,
    :type
  ]

  @type t :: %__MODULE__{
    :button_id => String.t | nil,
    :payload => String.t | nil,
    :title => String.t,
    :type => String.t
  }
end

defimpl Poison.Decoder, for: WhatsAPI.Model.StructsTemplateButton do
  def decode(value, _options) do
    value
  end
end

