# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WhatsAPI.Model.StructsSendMediaPayload do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :caption,
    :filename,
    :media_data,
    :media_type,
    :to
  ]

  @type t :: %__MODULE__{
    :caption => String.t | nil,
    :filename => String.t | nil,
    :media_data => WhatsAPI.Model.StructsFileUpload.t,
    :media_type => String.t,
    :to => String.t
  }
end

defimpl Poison.Decoder, for: WhatsAPI.Model.StructsSendMediaPayload do
  import WhatsAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:media_data, :struct, WhatsAPI.Model.StructsFileUpload, options)
  end
end

