# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WhatsAPI.Model.StructsListItem do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :description,
    :row_id,
    :title
  ]

  @type t :: %__MODULE__{
    :description => String.t | nil,
    :row_id => String.t | nil,
    :title => String.t
  }
end

defimpl Poison.Decoder, for: WhatsAPI.Model.StructsListItem do
  def decode(value, _options) do
    value
  end
end

