# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WhatsAPI.Model.TemplateButtonPayload do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :buttons,
    :content_text,
    :footer,
    :header,
    :to
  ]

  @type t :: %__MODULE__{
    :buttons => [WhatsAPI.Model.TemplateButton.t],
    :content_text => String.t | nil,
    :footer => String.t | nil,
    :header => String.t | nil,
    :to => String.t
  }
end

defimpl Poison.Decoder, for: WhatsAPI.Model.TemplateButtonPayload do
  import WhatsAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:buttons, :list, WhatsAPI.Model.TemplateButton, options)
  end
end

