# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WhatsAPI.Model.WebhookPayload do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :webhook_url
  ]

  @type t :: %__MODULE__{
    :webhook_url => String.t | nil
  }
end

defimpl Poison.Decoder, for: WhatsAPI.Model.WebhookPayload do
  def decode(value, _options) do
    value
  end
end

