# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WhatsAPIGo.Model.InstancesInstanceKeyGroupsGroupIdProfilePicPutRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :file
  ]

  @type t :: %__MODULE__{
    :file => String.t
  }
end

defimpl Poison.Decoder, for: WhatsAPIGo.Model.InstancesInstanceKeyGroupsGroupIdProfilePicPutRequest do
  def decode(value, _options) do
    value
  end
end

