# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WhatsAPIGo.Model.MainApiResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :data,
    :error,
    :message,
    :status
  ]

  @type t :: %__MODULE__{
    :data => map() | nil,
    :error => boolean() | nil,
    :message => String.t | nil,
    :status => integer() | nil
  }
end

defimpl Poison.Decoder, for: WhatsAPIGo.Model.MainApiResponse do
  def decode(value, _options) do
    value
  end
end

