# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WhatsAPIGo.Model.StructsFileUpload do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :direct_path,
    :file_enc_sha256,
    :file_length,
    :file_sha256,
    :media_key,
    :mime_type,
    :url
  ]

  @type t :: %__MODULE__{
    :direct_path => String.t,
    :file_enc_sha256 => [integer()],
    :file_length => integer(),
    :file_sha256 => [integer()],
    :media_key => [integer()],
    :mime_type => String.t,
    :url => String.t
  }
end

defimpl Poison.Decoder, for: WhatsAPIGo.Model.StructsFileUpload do
  def decode(value, _options) do
    value
  end
end

