# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WhatsAPIGo.Model.StructsReplyButton do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :button_id,
    :button_text
  ]

  @type t :: %__MODULE__{
    :button_id => String.t | nil,
    :button_text => String.t | nil
  }
end

defimpl Poison.Decoder, for: WhatsAPIGo.Model.StructsReplyButton do
  def decode(value, _options) do
    value
  end
end

