# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WhatsAPIGo.Model.StructsContactMessagePayload do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :to,
    :vcard
  ]

  @type t :: %__MODULE__{
    :to => String.t,
    :vcard => WhatsAPIGo.Model.StructsContactMessagePayloadVcard.t
  }
end

defimpl Poison.Decoder, for: WhatsAPIGo.Model.StructsContactMessagePayload do
  import WhatsAPIGo.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:vcard, :struct, WhatsAPIGo.Model.StructsContactMessagePayloadVcard, options)
  end
end

