# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WhatsAPIGo.Model.StructsTemplateButtonWithMediaPayload do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :buttons,
    :content_text,
    :footer,
    :media,
    :to
  ]

  @type t :: %__MODULE__{
    :buttons => [WhatsAPIGo.Model.StructsTemplateButton.t],
    :content_text => String.t | nil,
    :footer => String.t | nil,
    :media => WhatsAPIGo.Model.StructsFileUpload.t,
    :to => String.t
  }
end

defimpl Poison.Decoder, for: WhatsAPIGo.Model.StructsTemplateButtonWithMediaPayload do
  import WhatsAPIGo.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:buttons, :list, WhatsAPIGo.Model.StructsTemplateButton, options)
    |> deserialize(:media, :struct, WhatsAPIGo.Model.StructsFileUpload, options)
  end
end

