# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WhatsAPIGo.Model.StructsLocationMessagePayload do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :location,
    :to,
    :url
  ]

  @type t :: %__MODULE__{
    :location => WhatsAPIGo.Model.StructsLocationMessagePayloadLocation.t,
    :to => String.t,
    :url => String.t | nil
  }
end

defimpl Poison.Decoder, for: WhatsAPIGo.Model.StructsLocationMessagePayload do
  import WhatsAPIGo.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:location, :struct, WhatsAPIGo.Model.StructsLocationMessagePayloadLocation, options)
  end
end

