# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WhatsAPIGo.Model.StructsButtonMessagePayload do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :buttons,
    :footer_text,
    :header_text,
    :text,
    :to
  ]

  @type t :: %__MODULE__{
    :buttons => [WhatsAPIGo.Model.StructsReplyButton.t] | nil,
    :footer_text => String.t | nil,
    :header_text => String.t | nil,
    :text => String.t | nil,
    :to => String.t | nil
  }
end

defimpl Poison.Decoder, for: WhatsAPIGo.Model.StructsButtonMessagePayload do
  import WhatsAPIGo.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:buttons, :list, WhatsAPIGo.Model.StructsReplyButton, options)
  end
end

