# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WhatsAPIGo.Model.StructsGroupUpdateParticipantsPayload do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :participants
  ]

  @type t :: %__MODULE__{
    :participants => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: WhatsAPIGo.Model.StructsGroupUpdateParticipantsPayload do
  def decode(value, _options) do
    value
  end
end

